### ISSUE TITLE
系统接入SQL平台（Logical Plan和Physical Plan）

### ISSUE THREAD

**Issue by NKcqx** [NKcqx/CLIC#101]
扩展Logical Operator 使其支持关系型运算
Operator的粒度需要自由发挥一下
先不考虑和另一边的Optimizer结合做优化，先只考虑怎么生成Logical Plan ，之后怎么转为Physical Plan 等

DDL： 9.30日前

**Comment by DLUTLiuFengyi** [comment]
https://github.com/NKcqx/CLIC/commit/f25c6a0fad0a4863e1caf788db59f1df3f42eeb8

* 引入相关依赖和配置实现了支持java和scala混合编程
* Logical Plan引入了sql算子支持，明后两天添加荆老师组的Logical优化接口
* Physical Plan引入了sql算子支持，能跑通简单的spark sql执行流程，明天开始进行执行流程的规范化

**Comment by DLUTLiuFengyi** [comment]
https://github.com/NKcqx/CLIC/commit/391489523bece323e7dc0f01f1ee0892a4b74769
为与Spark SQL组对接作好准备
现在遇到一个影响较大的问题，这个问题是Spark SQL组需要解决的：在对Logical Plan进行优化时，需要启动SparkSession，而按照CLIC的设计思想，启动SparkSession这种工作只应该在Physical Plan阶段才能进行，而将SparkSession与Optimization剥离需要Spark SQL组进行较多的代码修改工作。
不过在CLIC中启动的SparkSession都是启动同一个Spark进程，只是把启动Spark的开销提前到Logcial Plan而已，所以与没接入优化功能之前在时间上的开销区别并不大。但目前这样显然是与CLIC的设计思想违背的。
这两天先把对接完全做好。

**Comment by DLUTLiuFengyi** [comment]
https://github.com/NKcqx/CLIC/commit/0a4ed09141b43fb64072d8a5bb4bc6757d6d12b8
进一步进行Spark SQL组与CLIC的对接工作
选择目前方案的原因有两点：
* Spark SQL组暂时也不知道该怎么解析他们返回的语法树里的参数
* 语法树的算子之间不是简单的线性依赖关系，而且Join算子现在也用不了
因此我现在在CLCI里写一个将他们返回的语法树转成SQL语句的类，再用Spark SQL平台执行这个SQL语句得出结果

**Comment by DLUTLiuFengyi** [comment]
https://github.com/NKcqx/CLIC/pull/126
SQL平台分支已用java重写，舍弃scala
* Logical Plan和Physical Plan测试已跑通并生成正确结果
* 删除关于scala的设置
* 关于spark_core的pom依赖导入已写到根目录的pom文件，其他地方的多余导入已删除
* 已通过checkstyle代码风格检查
