### ISSUE TITLE
多做几个实验

### ISSUE THREAD

**Issue by NKcqx** [NKcqx/CLIC#102]

**Comment by NKcqx** [comment]
1. 将数据传上HDFS，并使用新的HDFS算子进行测试
2. 继续扩大数据量，观察Workflow在Spark、Java、Spark + Java 的运行时间，是否能找到Spark < Java 时间的时候。
3. 将Case做完整，扩充UDF使其实现 “统计 用户-网站点击量”，而不是现在的 “仅单纯统计网站点击量”。 需要用到Join算子。

**Comment by NKcqx** [comment]
前两点的DDL： **9.30**前
第三点暂不做要求，看实验的效果决定

**Comment by StarpoSeven** [comment]
任务1测试时,之前直接线上测试, 在打包,安装环境上浪费过多时间,选择在本地安装hdfs测试,整体的workflow分为三个stage,第一个stage 存在的问题是,没有在javaExecuteOperator中添加,对应的反射, 修复后测试完成,验证了hdfssoure, hdfssink 算子的能正确运行,第二个stage,在spark上运行,其中FileSink,之前是使用文件传输数据,修改成hdfs方式之后, 存在的问题是无法正常的序列化数据,这个问题在9.30也都没有解决, 需要向齐翔,志伟请教,这部分spark代码,后续计划国庆回来后尽快完成, 第三个stage测试与任务2,在stage2bug修复后, 实验进度,会加快, 因为stage3中使用的算子,已经验证正确, 任务2,是在整体流程完成的情况下,只是扩大数据量,
新的DDL,计划是国庆回来的10.9号,10.10号这两天.

**Comment by StarpoSeven** [comment]
在10/13完成任务1

**Comment by StarpoSeven** [comment]
10/15: 将java与spark分开测试, 下午在志伟帮助下修改路径的bug(非常感谢🙏), 在晚上集群测试成功.周五计划,混合java与spark进行测试.

**Comment by StarpoSeven** [comment]
10/16: 周五测试:

1:修改cost, 混合jave与spark, 得到 job 和 dag yamel

2:打包jar, 上传到/nfs/data/zxp/Jar/JavaAndSpark

3:修改job (三个地方, 容器版本, jar包, udf和dag路径 ), 

4:上传job, dag到//nfs/data/zxp/smallTest/JavaAndSpark
问题:  java + spark + java 线上测试失败, 最终分别测试java和spark,从2G数据测试

**Comment by StarpoSeven** [comment]
10/22: 新的任务,增加case复杂度. 前面找到数据,不符合要求,同时, 如果使用广告点击, 在数据量4G时候Spark运行博报错

**Comment by StarpoSeven** [comment]
10/23:总结一周工作, 修复之前Spark线上测试报错, 分为两个方面, 1: 上周测试时,Spark平台一直运行很慢, 通过痛苦的排查,看日志,发现一直是在localhost单机运行,最终确定原因是代码设置没有切换成分布式, 也导致前面的实验重做,
2:上周测试一直出现java.lang.OutOfMemoryError: Java heap space,错误, 排除原因用了很长时间, 从怀疑环境问题, 切换配置, 到查询日志, 后面添加driver, executor的内存配置项,解决上述两点之后,Spark运行速度,大幅度提高.

**Comment by StarpoSeven** [comment]
10/28 java bug 仍然存在, 运行4G数据的时候, 仍然时间过长, 所使用的HDFS算子,是能正确运行的.

**Comment by StarpoSeven** [comment]
10/29 代码的问题查看没有找到问题, 现在怀疑是数据, 计划周五明天重新构建数据测试. 在554字节大小,Java6s运行, Spark分布式7秒, 这样的测试,感觉变量很多.

**Comment by StarpoSeven** [comment]
10/30 验证数据从最基础的5.6k数据开始测试java与spark,运行时间差异

**Comment by StarpoSeven** [comment]
11-3(周二)周一会后晚上补充spark本地实验, 周二和齐翔讨论后,觉得我我们的实验例子,过于简单,更好的是引入一个通用的数据处理平台中的例子,希望用CLICK实现wordconunt,进行测试,如果遇到缺失的算子,实现以后补充.

**Comment by NKcqx** [comment]
已另开issue
