### ISSUE TITLE
多个输入分支、跨平台、有中间结果生成情况下的Logical Plan生成尚有问题

### ISSUE THREAD

**Issue by DLUTLiuFengyi** [NKcqx/CLIC#122]
多个输入分支、跨平台、有中间结果生成情况下的Logical Plan生成尚有问题，问题出现在CLIC给每个平台自动封装的Source算子的个数不对。

比如说有这么个case：
* 第一条路是 Source1 -> Filter1
* 第二条路是 Source2 -> Filter2
* 两条路 Join 合并成一条路
* Sink

这个case的Logical Plan切分成3个Stage：
* Java Stage:
  Source1 + 自动生成的Sink
* Java Stage:
  Source2 + 自动生成的Sink
* Spark Stage:
  自动生成的Source + Filter1 + Filter2 + Join + Sink

最后一个Stage遇到问题，CLIC自动给这个Stage生成的Source算子只有一个，观察这个Stage的DAG图yaml文件可以看到Filter1和Filter2算子的上一个算子（Source）的id相同，就是说只有一条路的中间结果被传进这个DAG，另一条路没有传进来。需要在这个DAG的yaml文件补充上读取另一条路中间结果的Source算子才能跑通这个测试Join算子的case。

**Comment by NKcqx** [comment]
> 需要在这个DAG的yaml文件补充上读取另一条路中间结果的Source算子才能跑通这个测试Join算子的case。

这个先不做，这个case是因为所有相邻的`operator`都在不同平台上
可以先改下`operator`的`cost` 或者用 `DataQuanta` 里的新API `withTargetPlatform` 把相邻算子选择为同一平台即可
