### ISSUE TITLE
收敛依赖版本到父pom

### ISSUE THREAD

**Issue by isEdwardTang** [NKcqx/CLIC#133]
依赖包的随意添加经常造成依赖包冲突以及jar包的大小的膨胀，最合适的方式是将所有的依赖管理版本都放到父pom中，并仅在父pom中添加依赖的依赖包，比如日志管理等；而各个子项目不允许任意添加依赖，只允许引用父pom的依赖。因此需要清理下目前项目的依赖情况

**Comment by NKcqx** [comment]
#148
