### ISSUE TITLE
添加统计性能（时间）的相关类、方法

### ISSUE THREAD

**Issue by NKcqx** [NKcqx/CLIC#87]
添加类似监控器的东西，为每个Opt的运行过程记录时间，便于之后对比

**Comment by bob-du** [comment]
1.目前简单的log记录：
        每个stage的运行时间；
        输入文件的大小；
        输出文件的大小；
        stage中所包含的operator；
   log文件输出到nfs中；
2.后续log需要添加在stage中添加job标识，方便统计；
3.对于资源使用情况后续配合监控工具获取；
4.对于其他所需log记录的后续添加，例如修改 输入输出数据大小等。

**Comment by NKcqx** [comment]
Log文件能正常保存了吗？
还需要配置Promethus这类工具吗？

**Comment by bob-du** [comment]
这个Promethus监控工具以后根据需要再说吧
